name: nasa_api_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  envied: ^0.5.2
  http: ^1.1.2
  json_annotation: ^4.8.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  geolocator: ^10.1.0
  meta: ^1.10.0
  html: ^0.15.4
  url_launcher: ^6.2.4
  transparent_image: ^2.0.1
  google_fonts: ^6.1.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  envied_generator: ^0.5.2
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/images/apoc_placeholder.jpeg
    - lib/images/curiosity.jpeg
    - lib/images/mars_With_rover.jpeg
    - lib/images/spirit&opportunity.jpeg
    - lib/images/landing_bg.jpg
    - lib/images/earth.png
    - lib/images/jupiter.png
    - lib/images/mars.png
    - lib/images/mercury.png
    - lib/images/neptune.png
    - lib/images/saturn.png
    - lib/images/sun.png
    - lib/images/uranus.png
    - lib/images/venus.png
    - lib/images/pluto.png
    - lib/images/earthLarge.jpeg
    - lib/images/jupiterLarge.jpeg
    - lib/images/marsLarge.jpeg
    - lib/images/mercuryLarge.jpeg
    - lib/images/neptuneLarge.jpeg
    - lib/images/saturnLarge.jpeg
    - lib/images/sunLarge.jpeg
    - lib/images/uranusLarge.jpeg
    - lib/images/venusLarge.jpeg
    - lib/images/plutoLarge.jpeg