const planetDescriptions = {
  "earthDescription":
      'Earth is the third planet from the Sun and the only astronomical object known to harbor life. This is enabled by Earth being a water world, the only one in the Solar System sustaining liquid surface water. Almost all of Earth\'s water is contained in its global ocean, covering 70.8% of Earth\'s crust. The remaining 29.2% of Earth\'s crust is land, most of which is located in the form of continental landmasses within one hemisphere, Earth\'s land hemisphere. Most of Earth\'s land is somewhat humid and covered by vegetation, while large sheets of ice at Earth\'s polar deserts retain more water than Earth\'s groundwater, lakes, rivers and atmospheric water combined. Earth\'s crust consists of slowly moving tectonic plates, which interact to produce mountain ranges, volcanoes, and earthquakes. Earth has a liquid outer core that generates a magnetosphere capable of deflecting most of the destructive solar winds and cosmic radiation.',
  'sunDescription':
      'The Sun is the star at the center of the Solar System. It is a massive, hot ball of plasma, and it is inflated and heated by energy produced by nuclear fusion reactions at its core. Part of this internal energy gets emitted from the surface as light, ultraviolet, and infrared radiation, providing most of the energy for life on Earth. The Sun behaves dynamically as a magneto-alternator rather than a dynamo.',
  'mercuryDescription':
      'Mercury is the first planet from the Sun and the smallest in the Solar System. In English, it is named after the Roman god Mercurius (Mercury), god of commerce and communication, and the messenger of the gods. Mercury is classified as a terrestrial planet, with roughly the same surface gravity as Mars. The surface of Mercury is heavily cratered, as a result of countless impact events that have accumulated over billions of years. Its largest crater, Caloris Planitia, has a diameter of 1,550 km (960 mi) and one-third the diameter of the planet (4,880 km or 3,030 mi). Similarly to the Earth\'s Moon, Mercury\'s surface displays an expansive rupes system generated from thrust faults and bright ray systems formed by impact event remnants.',
  'venusDescription':
      'Venus is the second planet from the Sun. It has the densest atmosphere of all rocky bodies in the Solar System, so dense that at surface level and 92 atmospheres, it is a supercritical fluid. The planet\'s surface is dominated by volcanoes – there are 167 Venusian volcanoes that are over 100 km (60 mi) across. Venus has a diameter roughly equal to Earth\'s at 12,104 km (7,521 mi) and is classified as a terrestrial planet.',
  'marsDescription':
      'Mars is the fourth planet from the Sun. The surface of Mars is orange-red because it is covered in iron(III) oxide dust, giving it the nickname "the Red Planet".[21][22] Mars hosts many enormous extinct volcanos (such as Olympus Mons, 21.9 km or 13.6 mi tall) and one of the largest canyons in the Solar System (Valles Marineris, 4,000 km or 2,500 mi long). For comparison, Mars\'s diameter is 6,779 km (4,212 mi). It is classified as a terrestrial planet and is the second smallest of the Solar System\'s planets.',
  'jupiterDescription':
      'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, and slightly less than one one-thousandth the mass of the Sun. Jupiter orbits the Sun at a distance of 5.20 AU (778.5 Gm) with an orbital period of 11.86 years. Jupiter is the third brightest natural object in the Earth\'s night sky after the Moon and Venus, and it has been observed since prehistoric times. It was named after Jupiter, the chief deity of ancient Roman religion.',
  'saturnDescription':
      'Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine-and-a-half times that of Earth. It has only one-eighth the average density of Earth, but is over 95 times more massive.',
  'uranusDescription':
      'Uranus is the seventh planet from the Sun. It is a gaseous cyan-coloured ice giant. Most of the planet is made of water, ammonia, and methane in a supercritical phase of matter, which in astronomy is called \'ice\' or volatiles. The planet\'s atmosphere has a complex layered cloud structure and has the lowest minimum temperature of 49 K (−224 °C; −371 °F) out of all the Solar System\'s planets. It has a marked axial tilt of 82.23° with a retrograde rotation rate of 17 hours. This means that in an 84-Earth-year orbital period around the Sun, its poles get around 42 years of continuous sunlight, followed by 42 years of continuous darkness.',
  'neptuneDescription':
      'Neptune is the eighth and farthest planet from the Sun. It is the fourth-largest planet in the Solar System by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, and slightly more massive than its near-twin Uranus. Neptune is denser and physically smaller than Uranus because its greater mass causes more gravitational compression of its atmosphere. Being composed primarily of gases and liquids, it has no well-defined solid surface. The planet orbits the Sun once every 164.8 years at an orbital distance of 30.1 astronomical units (4.5 billion kilometres; 2.8 billion miles). It is named after the Roman god of the sea and has the astronomical symbol ♆, representing Neptune\'s trident.',
  'plutoDescription':
      'Pluto (minor-planet designation: 134340 Pluto) is a dwarf planet in the Kuiper belt, a ring of bodies beyond the orbit of Neptune. It is the ninth-largest and tenth-most-massive known object to directly orbit the Sun. It is the largest known trans-Neptunian object by volume, by a small margin, but is slightly less massive than Eris. Like other Kuiper belt objects, Pluto is made primarily of ice and rock and is much smaller than the inner planets. Pluto has only one sixth the mass of Earth\'s moon, and one third its volume.',
};
